version: "3"

networks:
  inception: {}

volumes:
    mariadb_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/home/data/mariadb
    wordpress_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/home/data/wordpress
    adminer_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/home/data/adminer

services:
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
       - DB_HOSTNAME=${DB_HOSTNAME}
       - WP_DB_NAME=${WP_DB_NAME}
       - MYSQL_USER=${MYSQL_USER}
       - MYSQL_PASSWORD=${MYSQL_PASSWORD}
       - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    image: mariadb
    container_name: MARIADB
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql:rw
    restart: unless-stopped

  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    container_name: WORDPRESS
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/wordpress:rw
    depends_on:
       - mariadb
    environment:
       - DB_HOSTNAME=${DB_HOSTNAME}
       - WP_DB_NAME=${WP_DB_NAME}
       - MYSQL_USER=${MYSQL_USER}
       - MYSQL_PASSWORD=${MYSQL_PASSWORD}
       - WP_TITLE=${WP_TITLE}
       - WP_ADMIN_USER=${WP_ADMIN_USER}
       - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
       - WP_ADMIN_MAIL=${WP_ADMIN_MAIL}
       - WP_USER=${WP_USER}
       - WP_USER_MAIL=${WP_USER_MAIL}
       - WP_USER_PASSWORD=${WP_USER_PASSWORD}
       - WP_URL=${WP_URL}
    restart: unless-stopped

  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: NGINX
    depends_on:
     - wordpress
    ports:
      - "4242:443"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/wordpress:ro
    restart: unless-stopped